//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InsuranceDBEntities1 : DbContext
    {
        public InsuranceDBEntities1()
            : base("name=InsuranceDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CaseType> CaseType { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Contract> Contract { get; set; }
        public virtual DbSet<InsuranceAgent> InsuranceAgent { get; set; }
        public virtual DbSet<InsuranceCase> InsuranceCase { get; set; }
        public virtual DbSet<InsuranceProgram> InsuranceProgram { get; set; }
        public virtual DbSet<Property> Property { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<LifestyleOptions> LifestyleOptions { get; set; }
        public virtual DbSet<TimingOptions> TimingOptions { get; set; }
    }
}
