//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceCase
    {
        public int CaseID { get; set; }
        public int ContractID { get; set; }
        public decimal PayoutAmount { get; set; }
        public System.DateTime Date { get; set; }
        public int CaseTypeID { get; set; }
        public Nullable<bool> signed { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> PayoutDate { get; set; }
        public string Comment { get; set; }
    
        public virtual CaseType CaseType { get; set; }
        public virtual Contract Contract { get; set; }
    }
}
